name: Reusable Action for PNPM and NX
description: Restore/Create cache for PNPM and NX
author: dipiash
branding:
  color: orange
  icon: package
runs:
  using: "composite"
  steps:
    - name: Restore cache for pnpm and node_modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.pnpm-store
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v4

    - uses: nrwl/nx-set-shas@v2

    - name: Cache Nx
      uses: actions/cache@v3
      with:
        path: node_modules/.cache/nx
        key: cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-type-check-${{ github.sha }}
        restore-keys: |
          cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-type-check-
          cache-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
